### ISSUE TITLE
Tópico 8 - Testar soluções de outros grupos 

### ISSUE THREAD

**Issue by gkimura** [gkimura/Avaliando_qualidade_dados_de_ocorrencia#9]
Utilizar o package para que outros grupos possam instalar as soluções em seus ambientes conda.

**Comment by rafaelloni** [comment]
Mencionei previamente que tinha criado um package, porém tinha feito algo errado. Estava testando agora a criação de package aqui com o Vitor, porém não da pra cirar package com arquivo no jupyter. Uma alternativa é passar todo código para o .py, entretanto o último método não vai funcionar, porque o plot do mapa só funciona no Jupyter.

**Comment by gkimura** [comment]
Vixe. Ok, vou passar o código pra .py e adicionar a minha solução do exercício 4, que não faz o plot do mapa.

**Comment by rafaelloni** [comment]
Beleza, ai posso colocar no package aqui.

**Comment by gkimura** [comment]
Pronto, já coloquei no repositório.

**Comment by gkimura** [comment]
Só veja se para criar o package não precisa tirar a parte que a gente tá rodando o programa, ou seja, se não precisa só empacotar a classe.
